### ISSUE TITLE
Can't show the complete neural network

### ISSUE THREAD

**Issue by houping** [Prodicode/ann-visualizer#10]
Hi Thanks for the contribution!

I have a small problem. I want to create a network with the input shape as 11. But the network I created by ant-visualizer cut one input off, only shows 10. I used the exact code as in the example. Please let me know how to fix this. Thanks! 
[network.gv.pdf](https://github.com/Prodicode/ann-visualizer/files/1986056/network.gv.pdf)

**Comment by jiangyiqun233** [comment]
I also meet the problem.
The first time I use it runs pretty good
![nn](https://user-images.githubusercontent.com/39370699/40171232-9b69e648-5a05-11e8-8a30-76475f7c91ea.png)
but the second time I got this.
![nn](https://user-images.githubusercontent.com/39370699/40171233-9b94145e-5a05-11e8-8cb0-aff71918ea45.png)
and the error is :
  File "C:\Users\nishitani\Anaconda3\envs\python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['dot.bat', '-Tpdf', '-O', '123.gv']' returned non-zero exit status 1.

**Comment by Prodicode** [comment]
The ann-visualizer library only displays a maximum of 10 nodes on a row (in order to look good), but you can see in the title "Input Layer" there is a (+1) to show that there is one more hidden node that is not shown.
