### ISSUE TITLE
Bias

### ISSUE THREAD

**Issue by endolith** [Prodicode/ann-visualizer#16]
Can you show bias nodes?

![bias_node_in_net 1](https://user-images.githubusercontent.com/58611/44622420-02271580-a886-11e8-8570-11b6ba4afb72.png)

![main-qimg-bf5a21006f36c6653a586b06da1a04f2](https://user-images.githubusercontent.com/58611/44622428-1ff47a80-a886-11e8-8725-e364c07b7cb8.png)

![a-schematic-diagram-of-artificial-neural-network-and-architecture-of-the-feed-forward_w640 1](https://user-images.githubusercontent.com/58611/44622431-2b47a600-a886-11e8-8412-983f1a29747e.jpg)

**Comment by RedaOps** [comment]
Currently, the library doesn't supoort these types of nodes.

**Comment by endolith** [comment]
Keras has bias nodes when you set `use_bias=True`. https://keras.io/layers/core/#dense

**Comment by endolith** [comment]
It would just be an additional node on that layer, not connected to previous layer, with a different color or shape or filled with "1" to indicate it's a bias node.

**Comment by RedaOps** [comment]
I will check it out when I have some time. Right now i am busy with other ptojects, but thanks for the feedback and suggestion!
