### ISSUE TITLE
ANN Visualizer: Layer not supported for visualizing

### ISSUE THREAD

**Issue by jwz-ecust** [Prodicode/ann-visualizer#5]
```
from keras.models import Sequential, Model
from keras.layers import Dense, Activation, Input
from ann_visualizer.visualize import ann_viz


suboutputs = []

for i in range(30):
    model = Sequential([
        Dense(80, input_shape=(4,)),
        Activation('sigmoid'),
        Dense(60, input_shape=(80,)),
        Activation('sigmoid'),
        Dense(1, input_shape=(60,)),
    ])

    x = Input(shape=(1,), tensor=model.layers[-1].output)
    suboutputs.append(x)

y = Dense(1)(suboutputs[0])

mm = Model(inputs=suboutputs, outputs=y)

ann_viz(mm, title="net")
```
Here is my code

## Results:
```
Traceback (most recent call last):
  File "/home/xxx/keras_plot.py", line 30, in <module>
    ann_viz(mm, title="net")
  File "/home/xxx/.anaconda3/lib/python3.6/site-packages/ann_visualizer/visualize.py", line 117, in ann_viz
    raise ValueError("ANN Visualizer: Layer not supported for visualizing");
ValueError: ANN Visualizer: Layer not supported for visualizing
```

**Comment by Prodicode** [comment]
Hi!

Can you try including the activation functions when declaring the dense layers?

Instead of this:
```
model = Sequential([
        Dense(80, input_shape=(4,)),
        Activation('sigmoid'),
        Dense(60, input_shape=(80,)),
        Activation('sigmoid'),
        Dense(1, input_shape=(60,)),
    ])
```


Try this: 

```
model = Sequential([
        Dense(80, input_shape=(4,), activation='sigmoid'),
        Dense(60, input_shape=(80,), activation='sigmoid'),
        Dense(1, input_shape=(60,)),
    ])
```

**Comment by jwz-ecust** [comment]
@Prodicode Thx! I tried. It doesn't work and still shows "Layer not supported for visualizing".

**Comment by Prodicode** [comment]
I notice that you are passing a Model object to the `ann_viz()` function. You can try passing an Sequential object.

Look at the example in Readme where it visualizez a simple Dense Neural Network, and build your model using the `Sequential().add()` function. Here's an example:

```python
model = Sequential()
model.add(Dense(80, input_shape=(4,), activation='sigmoid'));

#etc
#Add your other layers
#Compile NN
```

**Comment by jwz-ecust** [comment]
@Prodicode I need to use "Layer". But it not support "Layer".

**Comment by Prodicode** [comment]
It does not support Activation layers yet, but you can include the activation function when declaring the Dense layer. I gave an example above. Either way, only pass Sequential objects to the `ann_viz()` function. I will add support for Activation layers as soon as possible.

**Comment by jwz-ecust** [comment]
@Prodicode  Thx

**Comment by Prodicode** [comment]
de4970c61b99314b0caddeddfd95bc5833993a91 - Release v2.2

Now supports Activation layers

Here's a code example:

```python
import keras;
from keras.models import Sequential;
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout, Activation;
import json;

network = Sequential();


def build_cnn_model():
  model = keras.models.Sequential()

  model.add(Dense(80, input_shape=(4,)));
  model.add(Activation('sigmoid'));
  model.add(Dense(60));
  model.add(Activation('sigmoid'));
  model.add(Dense(1));

  return model

network = build_cnn_model();

from visualize import ann_viz;

ann_viz(network, title="", view=True);

print(network.layers[1].get_config());

```

It will output the following:
![network gv-1](https://user-images.githubusercontent.com/32748771/38524223-9266e5f4-3c56-11e8-8532-53cd866cd88b.png)

**Comment by endolith** [comment]
The path through the activation layer is in1→out1, in2→out2, etc. correct?  There's no interaction between the different paths inside the box?  Could you show this by representing each activation function as a separate box instead of having them all go into one box and then come back out?  Something like:

![feed-forward-neural-network-with-sigmoid-activation-function-x-i-i-1p-input_w640 1](https://user-images.githubusercontent.com/58611/44609164-a9437880-a7c4-11e8-9093-25aaa9c72442.jpg)

![architecture-of-the-neural-network-consisting-of-four-successive-layers-a-linear-layer_w640 1](https://user-images.githubusercontent.com/58611/44609271-fc1d3000-a7c4-11e8-8c65-eea11912e9f5.jpg)

but not necessarily showing the actual function curve.  I'm just referring to the boxes.

(Or there is interaction between the inputs with certain activation functions?  In which case this would not be a good visualization for those.)

**Comment by endolith** [comment]
Also for "Layer not supported" it could just show a blank box layer instead of erroring out
