### ISSUE TITLE
running example Error

### ISSUE THREAD

**Issue by nagasawa-masami** [Prodicode/ann-visualizer#8]
Traceback (most recent call last):
  File "anntest.py", line 21, in <module>
    ann_viz(network)
  File "/home/masami/anaconda3/lib/python3.6/site-packages/ann_visualizer/visualize.py", line 88, in ann_viz
    g.attr(splines="false", nodesep='1', ranksep='2');
TypeError: attr() missing 1 required positional argument: 'kw'

**Comment by Prodicode** [comment]
What version of ann-visualizer are you using?

**Comment by nagasawa-masami** [comment]
version 2.2 and my code:
import keras
from keras.models import Sequential
from keras.layers import Dense

network = Sequential()
network.add(Dense(units=6,
                  activation='relu',
                    kernel_initializer='uniform',
                    input_dim=11))

network.add(Dense(units=6,
                  activation='relu',
                  kernel_initializer='uniform'))

network.add(Dense(units=1,
                  activation='sigmoid',
                  kernel_initializer='uniform'))

from ann_visualizer.visualize import ann_viz

ann_viz(network)

**Comment by nagasawa-masami** [comment]
python 3.6

**Comment by Prodicode** [comment]
Can you try running the whole thing on python 3.5 ?

**Comment by Prodicode** [comment]
0248a8d1a1f4b965ebe6109e1bfec76114145865

Should have been fixed in Release v2.4
